language: node_js

node_js:
  - '14'

script:
- npm install
- npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: travis-bucket-cjswoduddn
  region: ap-northeast-2
  skip_cleanup: true
  local_dir: build
  on:
    branch: main

  # http://www.yamllint.com/